
services:
  iiif-manifest:
    image: inuits-elody-${TRAEFIK_PROJECT_NAMESPACE}-iiif:local-dev
    platform: linux/amd64
    build:
      context: inuits-dams-iiif-manifest-mapper
      dockerfile: docker/Dockerfile
      target: development-stage
    environment:
      - DOCKER_BUILDKIT

      - COLLECTION_API_URL
      - IMAGE_API_URL
      - IMAGE_API_URL_EXT
      - JOB_API_URL
      - PRESENTATION_API_URL

      - REQUIRE_TOKEN
      - STATIC_JWT
      - STATIC_ISSUER
      - STATIC_PUBLIC_KEY
      - ROLE_PERMISSION_FILE
      - SUPER_ADMIN_ROLE
      - REMOTE_TOKEN_VALIDATION

      - APP_ENV=dev
    networks:
      elody:
        aliases:
          - iiif-manifest-${PROJECT_FOLDER}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TRAEFIK_PROJECT_NAMESPACE}-iiif-manifest.rule=Host(`iiif-manifest.${PROJECT_DOMAIN}`) && PathPrefix(`/`)" # TODO change Host to api.[...]
      - "traefik.http.services.${TRAEFIK_PROJECT_NAMESPACE}-iiif-manifest.loadbalancer.server.port=5000"
    volumes:
      - "./inuits-dams-iiif-manifest-mapper/api:/app/api"
    profiles:
      - backend

  cantaloupe:
    image: registry-dev.cloud.inuits.io/inuits/dams-cantaloupe:latest
    platform: linux/amd64
    build:
      context: dams-cantaloupe
      dockerfile: docker/Dockerfile
    environment:
      - COLLECTION_API_URL
      - STORAGE_API_URL
      - STORAGE_API_URL_EXT
      - STATIC_JWT
    volumes:
      - ./docker-compose/cantaloupe/cantaloupe.properties:/etc/cantaloupe/cantaloupe.properties
    networks:
      elody:
       aliases:
        - cantaloupe-${PROJECT_FOLDER}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TRAEFIK_PROJECT_NAMESPACE}-cantaloupe.rule=Host(`cantaloupe.${PROJECT_DOMAIN}`) && PathPrefix(`/`)" # TODO change Host to api.[...]
      - "traefik.http.services.${TRAEFIK_PROJECT_NAMESPACE}-cantaloupe.loadbalancer.server.port=8182"

networks:
  traefik:
  elody:
    name: elody
