services:
  ocr-service:
      image: inuits-elody-${TRAEFIK_PROJECT_NAMESPACE}-ocr-service:local-dev
      platform: linux/amd64
      build:
        context: ocr-service
        dockerfile: docker/Dockerfile
        target: development-stage
      environment:
        - APPS_MANIFEST
        - DOCKER_BUILDKIT

        - CLIENT_PDF_FILENAME
        - CLIENT_IMAGE_PATH
        - CLIENT_PDF_PATH
        - TESSDATA_PREFIX

        - AMQP_MANAGER
        - MQ_URL
        - MQ_EXCHANGE
        - DURABLE_EXCHANGE
        - AUTO_DELETE_EXCHANGE
        - EVENT_DELAY=0

        - COLLECTION_API_URL
        - STORAGE_API_URL
        - JOB_API_URL

        - AUTO_CREATE_TENANTS
        - IGNORE_PERMISSIONS
        - ALLOW_ANONYMOUS_USERS
        - ALLOWED_ISSUERS

        - TOKEN_SCHEMA
        - TENANT_DEFINING_TYPES
        - STATIC_JWT
        - STATIC_ISSUER
        - STATIC_PUBLIC_KEY
        - ROLE_SCOPE_MAPPING
        - SUPER_ADMIN_ROLE
        - APP_ENV=dev
      volumes:
        - "./clients/${PROJECT_FOLDER}/docker-compose/elody/role_scope_mapping.json:/app/role_scope_mapping.json"
        - "./clients/${PROJECT_FOLDER}/docker-compose/storage-api/app_list.json:/app/api/apps/app_list.json"
        - "./clients/${PROJECT_FOLDER}/docker-compose/elody/token_schema.json:/app/token_schema.json"
        - "./ocr-service/api:/app/api"
      networks:
        elody:
          aliases:
          - ocr-service-${PROJECT_FOLDER}
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${TRAEFIK_PROJECT_NAMESPACE}-ocr-service.rule=Host(`ocr-service.${PROJECT_DOMAIN}`) && PathPrefix(`/`)" # TODO change Host to api.[...]
        - "traefik.http.services.${TRAEFIK_PROJECT_NAMESPACE}-ocr-service.loadbalancer.server.port=5000"
      profiles:
        - backend
